/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 * Copyright (C) 2000-2021 Synology Inc.
 */
#ifndef _UAPI_LINUX_SYNO_H
#define _UAPI_LINUX_SYNO_H

/* syno_autoconf.h was generated by modified /scripts/kconfig/conf (SYNO_EXPORT_CONFIG) */
#ifndef __KERNEL__
#include <linux/syno_autoconf.h>
#endif

#ifndef LINUX_VERSION_CODE
#include <linux/version.h>
#endif
#define SYNO_HAVE_KERNEL_VERSION(a,b,c) (LINUX_VERSION_CODE >= KERNEL_VERSION((a),(b),(c)) )

#ifdef CONFIG_SYNO_FS_ARCHIVE_BIT
#define SYNO_ARCHIVE_BIT
#if defined (F_CLEAR_ARCHIVE) || defined (F_SETSMB_ARCHIVE) || defined (F_SETSMB_HIDDEN) || \
    defined (F_SETSMB_SYSTEM) || defined (F_CLRSMB_ARCHIVE) || defined (F_CLRSMB_HIDDEN) || \
    defined (F_CLRSMB_SYSTEM) || defined (F_CLEAR_S3_ARCHIVE) ||               \
    defined (F_SETSMB_SPARSE) || defined (F_CLRSMB_SPARSE)
#error "Samba archive bit redefine."
#endif

#ifdef CONFIG_SYNO_FS_WINACL
#define SYNO_FS_SYNO_ACL
#if defined (F_CLRSMB_READONLY) || defined (F_SETSMB_READONLY) ||              \
    defined (F_CLRACL_INHERIT)  || defined (F_SETACL_INHERIT)  ||              \
    defined (F_CLRACL_OWNER_IS_GROUP) || defined (F_SETACL_OWNER_IS_GROUP) ||  \
    defined (F_SETACL_SUPPORT) || defined (F_SETACL_SUPPORT)
#error "ACL archive bit redefine."
#endif /* ACL archive bit redefine. */
#endif /* CONFIG_SYNO_FS_WINACL */

#define SYNO_FCNTL_BASE             513
#define F_CLEAR_ARCHIVE             (SYNO_FCNTL_BASE + 0)
#define F_SETSMB_ARCHIVE            (SYNO_FCNTL_BASE + 1)
#define F_SETSMB_HIDDEN             (SYNO_FCNTL_BASE + 2)
#define F_SETSMB_SYSTEM             (SYNO_FCNTL_BASE + 3)
#define F_CLRSMB_ARCHIVE            (SYNO_FCNTL_BASE + 4)
#define F_CLRSMB_HIDDEN             (SYNO_FCNTL_BASE + 5)
#define F_CLRSMB_SYSTEM             (SYNO_FCNTL_BASE + 6)
#define F_CLEAR_S3_ARCHIVE          (SYNO_FCNTL_BASE + 7)

#ifdef CONFIG_SYNO_FS_WINACL
#define F_CLRSMB_READONLY           (SYNO_FCNTL_BASE + 8)
#define F_SETSMB_READONLY           (SYNO_FCNTL_BASE + 9)
#define F_CLRACL_INHERIT            (SYNO_FCNTL_BASE + 10)
#define F_SETACL_INHERIT            (SYNO_FCNTL_BASE + 11)
#define F_CLRACL_HAS_ACL            (SYNO_FCNTL_BASE + 12)
#define F_SETACL_HAS_ACL            (SYNO_FCNTL_BASE + 13)
#define F_CLRACL_SUPPORT            (SYNO_FCNTL_BASE + 14)
#define F_SETACL_SUPPORT            (SYNO_FCNTL_BASE + 15)
#define F_CLRACL_OWNER_IS_GROUP     (SYNO_FCNTL_BASE + 16)
#define F_SETACL_OWNER_IS_GROUP     (SYNO_FCNTL_BASE + 17)
#define F_SETSMB_SPARSE             (SYNO_FCNTL_BASE + 18)
#define F_CLRSMB_SPARSE             (SYNO_FCNTL_BASE + 19)
#define SYNO_FCNTL_LAST             F_CLRSMB_SPARSE
#else /* CONFIG_SYNO_FS_WINACL */
#define F_SETSMB_SPARSE             (SYNO_FCNTL_BASE + 8)
#define F_CLRSMB_SPARSE             (SYNO_FCNTL_BASE + 9)
#define SYNO_FCNTL_LAST             F_CLRSMB_SPARSE
#endif /* CONFIG_SYNO_FS_WINACL */
#endif /* CONFIG_SYNO_FS_ARCHIVE_BIT */

#ifdef CONFIG_SYNO_MD_STATUS_GET
#define SYNO_RAID_STATUS
#endif /* CONFIG_SYNO_MD_STATUS_GET */

#ifdef CONFIG_SYNO_FS_STAT
#define SYNO_STAT
#endif /* CONFIG_SYNO_FS_STAT */

#ifdef CONFIG_SYNO_FS_ARCHIVE_VERSION
#define SYNO_ARCHIVE_VERSION
#endif /* CONFIG_SYNO_FS_ARCHIVE_VERSION */

/**
 * Fix: DSM #103889
 * Dsc: Add notification for unsupported SFP+
 */
#if defined (CONFIG_SYNO_SFP_UNSUPPORTED_NOTIFY) && !defined (__ASSEMBLER__)
typedef enum
{
	SFP_NOTIFY_UNSET 			= 0,
	SFP_NOTIFY_NOT_SUPPORT_DROP	= 1,	/* Interface might drop. ex: ixgbe */
	SFP_NOTIFY_NOT_SUPPORT_WARN = 2		/* Driver report not support but it might still work */
} SYNO_SFP_UNSUPPORTED_NOTIFY_TYPE;
#endif /* CONFIG_SYNO_SFP_UNSUPPORTED_NOTIFY */

#ifdef CONFIG_SYNO_FS_CASELESS_STAT
#define SYNO_UNICODE_STAT
#endif /* CONFIG_SYNO_FS_CASELESS_STAT */

#ifdef CONFIG_SYNO_DISK_HIBERNATION
#define SD_IOCTL_IDLE 4746
#define SD_IOCTL_SUPPORT_SLEEP 4747
#endif /* CONFIG_SYNO_DISK_HIBERNATION */

#ifdef CONFIG_SYNO_SAS_HOST_DISK_LED_CTRL
#define SD_IOCTL_SASHOST_DISK_LED 4755
#endif /* CONFIG_SYNO_SAS_HOST_DISK_LED_CTRL */

/*
 * FIXME: The following legacy definitions are referred by userspace projects,
 * but do not depend on any kernel configs. They should be moved to a proper
 * project such as synoplatformconfig.
 */
#ifndef __KERNEL__
#define SYNO_INDEXING
#define SYNO_EA
#endif /* __KERNEL__ */

/**
 * Dsc: USB copy support
 *      use port number 99 to indicate USBCOPY port
 */
#ifdef CONFIG_SYNO_USB_COPY
#define USBCOPY_PORT_LOCATION 99
#endif /* CONFIG_SYNO_USB_COPY */

#endif /* _UAPI_LINUX_SYNO_H */
